version: "1.0.{build}"
image: Visual Studio 2019
branches:
  only:
    - master
init:
  - cmd: git config --global core.autocrlf true
#cache:
#  - C:\ProgramData\chocolatey\bin -> appveyor.yml
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
before_build:
  - choco install opencover.portable
  - choco install codecov
  #  - ps: >-
  #      Get-ChildItem .\ -include packages.lock.json -Recurse | foreach ($_) { remove-item $_.fullname -Force }
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build --configuration Release --no-restore
test_script:
  - cmd: dotnet test  --configuration Release --no-build --no-restore --verbosity minimal --test-adapter-path:. --logger:Appveyor /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:MergeWith="../TestResults/coverage.json"  /p:CoverletOutputFormat=lcov
deploy: off
