name: Build and Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Nuget
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run Tests
        run: |
          dotnet test Tests/TestCI.DAL.Tests/TestCI.DAL.Tests.csproj  --no-build --verbosity minimal --configuration Release /p:CoverletOutput=../TestResults/coverage.json /p:CoverletOutputFormat=json
          dotnet test Tests/TestCI.HostedService.Tests/TestCI.HostedService.Tests.csproj --no-build --verbosity minimal --configuration Release /p:CoverletOutput=../TestResults/coverage.json /p:MergeWith=../TestResults/coverlet.json /p:CoverletOutputFormat=json
          dotnet test Tests/TestCI.Web.Tests/TestCI.Web.Tests.csproj --no-build --verbosity minimal --configuration Release /p:CoverletOutput=../TestResults/coverage.json /p:MergeWith=../TestResults/coverlet.json /p:CoverletOutput=../TestResults/coverage.opencover.xml  /p:CoverletOutputFormat=opencover
          dotnet test Tests/TestCI.Modules.Tests/TestCI.Modules.Tests.csproj --no-build --verbosity minimal --configuration Release
      - name: Publish coverage report to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: >
            ./Tests/TestResults/coverage.opencover.xml,
            ./Tests/TestResults/TestCI.Modules.Tests.coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
#           dotnet test Tests/TestCI.Modules.Tests/TestCI.Modules.Tests.csproj --no-build --verbosity minimal --configuration Release /p:CollectCoverage=true /p:CoverletOutput=../TestResults/ /p:MergeWith=../TestResults/coverlet.json
